export const rec4poCarrierListToMap = [
    { id: 1, displayName: "Dachser (pickup)", shortName: "Dachser (pickup)" },
    { id: 2, displayName: "DHL", shortName: "DHL" },
    { id: 3, displayName: "DPD-CZ (pickup)", shortName: "DPD-CZ" },
    { id: 4, displayName: "DPD", shortName: "DPD" },
    { id: 5, displayName: "DPD-RO (pickup)", shortName: "DPD-RO (pickup)" },
    {
        id: 6,
        displayName: "ExpressOne/Intime (pickup)",
        shortName: "Express One SK/Intime (pickup)",
    },
    { id: 7, displayName: "Futar (pickup)", shortName: "Futar (pickup)" },
    { id: 8, displayName: "Geis-CZ (pickup)", shortName: "Geis-CZ(pickup)" },
    { id: 9, displayName: "Geis-SK (pickup)", shortName: "Geis-SK (pickup)" },
    { id: 10, displayName: "GLS", shortName: "GLS" },
    { id: 11, displayName: "GLS-HR (pickup)", shortName: "GLS-HR (pickup)" },
    { id: 12, displayName: "GLS-HU (pickup)", shortName: "GLS-HU (pickup)" },
    { id: 13, displayName: "GLS-SI (pickup)", shortName: "GLS-SI (pickup)" },
    { id: 14, displayName: "Hart-SI (pickup)", shortName: "Hart-SI (pickup)" },
    { id: 15, displayName: "HES (pickup)", shortName: "HES (pickup)" },
    { id: 16, displayName: "Rhenus (pickup)", shortName: "Rhenus" }, // Not working
    { id: 17, displayName: "SPS (pickup)", shortName: "SPS" },
    { id: 18, displayName: "UPS", shortName: "UPS" },
];

export const warehouseMapping = [
    { customerCountry: "FR", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "AT", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "BE", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "CH", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "DE", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "DK", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "EE", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "ES", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "FI", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "GB", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "GG", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "GR", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "IE", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "IT", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "JE", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "LT", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "LU", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "MC", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "NL", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "PT", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "SE", warehouse: "DE", allowedWarehouseId: 1 },
    { customerCountry: "BG", warehouse: "SK", allowedWarehouseId: 2 },
    { customerCountry: "CZ", warehouse: "SK", allowedWarehouseId: 2 },
    { customerCountry: "HR", warehouse: "SK", allowedWarehouseId: 2 },
    { customerCountry: "HU", warehouse: "SK", allowedWarehouseId: 2 },
    { customerCountry: "PL", warehouse: "SK", allowedWarehouseId: 2 },
    { customerCountry: "RO", warehouse: "SK", allowedWarehouseId: 2 },
    { customerCountry: "SI", warehouse: "SK", allowedWarehouseId: 2 },
    { customerCountry: "SK", warehouse: "SK", allowedWarehouseId: 2 },
];